-- MySQL Script generated by MySQL Workbench
-- Sun Mar 23 13:40:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trainer` (
  `t_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone_no` VARCHAR(15) NULL,
  `experience` FLOAT NOT NULL,
  PRIMARY KEY (`t_id`),
  UNIQUE INDEX `phone_no_UNIQUE` (`phone_no` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `DOB` DATE NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `phone_no` VARCHAR(15) NULL,
  `height` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `trainer_t_id` INT NOT NULL,
  PRIMARY KEY (`u_id`),
  UNIQUE INDEX `phone_no_UNIQUE` (`phone_no` ASC) VISIBLE,
  INDEX `fk_user_trainer1_idx` (`trainer_t_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_trainer1`
    FOREIGN KEY (`trainer_t_id`)
    REFERENCES `mydb`.`trainer` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`health_metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`health_metrics` (
  `m_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `weight` FLOAT NOT NULL,
  `height` FLOAT NOT NULL,
  `BMI` FLOAT GENERATED ALWAYS AS (weight / (height * height)) STORED,
  `heart_rate` INT NULL,
  `BP` VARCHAR(20) NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`m_id`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workout` (
  `w_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `duration` TIME NOT NULL,
  `difficulty` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`w_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trainer_has_workout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trainer_has_workout` (
  `trainer_t_id` INT NOT NULL,
  `workout_w_id` INT NOT NULL,
  PRIMARY KEY (`trainer_t_id`, `workout_w_id`),
  INDEX `fk_trainer_has_workout_workout1_idx` (`workout_w_id` ASC) VISIBLE,
  INDEX `fk_trainer_has_workout_trainer1_idx` (`trainer_t_id` ASC) VISIBLE,
  CONSTRAINT `fk_trainer_has_workout_trainer1`
    FOREIGN KEY (`trainer_t_id`)
    REFERENCES `mydb`.`trainer` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainer_has_workout_workout1`
    FOREIGN KEY (`workout_w_id`)
    REFERENCES `mydb`.`workout` (`w_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercise` (
  `e_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `trainer_t_id` INT NOT NULL,
  PRIMARY KEY (`e_id`),
  INDEX `fk_exercise_trainer1_idx` (`trainer_t_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercise_trainer1`
    FOREIGN KEY (`trainer_t_id`)
    REFERENCES `mydb`.`trainer` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workout_has_exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workout_has_exercise` (
  `workout_w_id` INT NOT NULL,
  `exercise_e_id` INT NOT NULL,
  `REPS` INT NOT NULL,
  `SETS` INT NOT NULL,
  PRIMARY KEY (`workout_w_id`, `exercise_e_id`),
  INDEX `fk_workout_has_exercise_exercise1_idx` (`exercise_e_id` ASC) VISIBLE,
  INDEX `fk_workout_has_exercise_workout1_idx` (`workout_w_id` ASC) VISIBLE,
  CONSTRAINT `fk_workout_has_exercise_workout1`
    FOREIGN KEY (`workout_w_id`)
    REFERENCES `mydb`.`workout` (`w_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workout_has_exercise_exercise1`
    FOREIGN KEY (`exercise_e_id`)
    REFERENCES `mydb`.`exercise` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food` (
  `f_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `calories` FLOAT NOT NULL,
  `protein` FLOAT NOT NULL,
  `fat` FLOAT NOT NULL,
  `carbs` FLOAT NOT NULL,
  `trainer_t_id` INT NOT NULL,
  PRIMARY KEY (`f_id`),
  INDEX `fk_food_trainer1_idx` (`trainer_t_id` ASC) VISIBLE,
  CONSTRAINT `fk_food_trainer1`
    FOREIGN KEY (`trainer_t_id`)
    REFERENCES `mydb`.`trainer` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diet` (
  `d_id` INT NOT NULL AUTO_INCREMENT,
  `total_cals` FLOAT,
  `total_protein` FLOAT,
  `total_fat` FLOAT,
  `total_carbs` FLOAT,
  PRIMARY KEY (`d_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diet_has_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diet_has_food` (
  `diet_d_id` INT NOT NULL,
  `food_f_id` INT NOT NULL,
  PRIMARY KEY (`diet_d_id`, `food_f_id`),
  INDEX `fk_diet_has_food_food1_idx` (`food_f_id` ASC) VISIBLE,
  INDEX `fk_diet_has_food_diet1_idx` (`diet_d_id` ASC) VISIBLE,
  CONSTRAINT `fk_diet_has_food_diet1`
    FOREIGN KEY (`diet_d_id`)
    REFERENCES `mydb`.`diet` (`d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diet_has_food_food1`
    FOREIGN KEY (`food_f_id`)
    REFERENCES `mydb`.`food` (`f_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trainer_has_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trainer_has_diet` (
  `trainer_t_id` INT NOT NULL,
  `diet_d_id` INT NOT NULL,
  PRIMARY KEY (`trainer_t_id`, `diet_d_id`),
  INDEX `fk_trainer_has_diet_diet1_idx` (`diet_d_id` ASC) VISIBLE,
  INDEX `fk_trainer_has_diet_trainer1_idx` (`trainer_t_id` ASC) VISIBLE,
  CONSTRAINT `fk_trainer_has_diet_trainer1`
    FOREIGN KEY (`trainer_t_id`)
    REFERENCES `mydb`.`trainer` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainer_has_diet_diet1`
    FOREIGN KEY (`diet_d_id`)
    REFERENCES `mydb`.`diet` (`d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_diets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_diets` (
  `user_id` INT NOT NULL,
  `trainer_id` INT NOT NULL,
  `diet_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `trainer_id`, `diet_id`),
  INDEX `fk_user_has_trainer_has_diet_trainer_has_diet1_idx` (`trainer_id` ASC, `diet_id` ASC) VISIBLE,
  INDEX `fk_user_has_trainer_has_diet_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_trainer_has_diet_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_trainer_has_diet_trainer_has_diet1`
    FOREIGN KEY (`trainer_id` , `diet_id`)
    REFERENCES `mydb`.`trainer_has_diet` (`trainer_t_id` , `diet_d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_workouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_workouts` (
  `user_id` INT NOT NULL,
  `trainer_id` INT NOT NULL,
  `workout_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `trainer_id`, `workout_id`),
  INDEX `fk_user_has_trainer_has_workout_trainer_has_workout1_idx` (`trainer_id` ASC, `workout_id` ASC) VISIBLE,
  INDEX `fk_user_has_trainer_has_workout_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_trainer_has_workout_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_trainer_has_workout_trainer_has_workout1`
    FOREIGN KEY (`trainer_id` , `workout_id`)
    REFERENCES `mydb`.`trainer_has_workout` (`trainer_t_id` , `workout_w_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
